on:
  push

name: Test Find Issue Key

jobs:
  test-find-issue-key:
    name: Find Issue Key
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Find issue key in commit messages
      id: find
      uses: ./
      with:
        string: ${{event.commits.map(c => c.message).join(' ')}}

    - name: Find issue info
      run: echo "Issue ${{ steps.find.outputs.issue }} was found"
